# Generated by Django 5.1.7 on 2025-04-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_genre_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('pubname', models.CharField(max_length=100)),
                ('pubcity', models.CharField(max_length=100)),
                ('pubemail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app4.publisher'),
        ),
    ]
